spring.application.name=habit_tracker

# Configurações de Conexão com o PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/habit_tracker
spring.datasource.username=admin
spring.datasource.password=admin123

# Configuração do Hibernate (JPA)
# 'update' cria as tabelas automaticamente baseado nas suas classes Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Mostra o SQL gerado no console (ajuda a debugar)
spring.jpa.show-sql=true